apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: prajwalheaptrace/python-app:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: python-app-secret
