apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Enable alpha plugins for Kustomize to allow ksops plugin usage
  kustomize.buildOptions: "--enable-alpha-plugins"
